## Dataloader
* reference : Natural language processing with PYTORCH

In [1]:
import os
os.environ["CUDA_VISIBLE_DEVICES"]="0,1"

In [9]:
import os, re, string

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader
from tqdm import notebook

In [6]:
if torch.cuda.device_count()>1:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
elif torch.cuda.device_count()>0:
    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

In [15]:
"""
data shape
rating, review, split
negative, "sentence", train
positive, "sentence", train
"""
f1_s = "/home/bwlee/data/yelp_review_polarity_csv/reviews_with_splits_full.csv"

#df1 = pd.read_csv(f1_s, header=0)
df1 = pd.read_csv(f1_s, header=0, nrows=1000)
#df1 = pd.read_csv(f1_s, header=0, skiprows=lambda x: x%5>0)
label0 = []
for i in df1.index: # change this for getting info based on previous day market move
    if df1['rating'].iloc[i] == 'positive':
        label0.append(1)
    else:
        label0.append(0)
df1['rating'] = label0

In [16]:
df1

     rating                                             review  split
0         0  the entrance was the impressive thing about th...  train
1         0  i m a mclover , and i had no problem nwith the...  train
2         0  less than good here , not terrible , but i see...  train
3         0  i don t know if i can ever bring myself to go ...  train
4         0  food was ok good but the service was terrible ...  train
..      ...                                                ...    ...
995       0  i ve given this place so many chances and it a...  train
996       0  ordered from the ayce menu and some of the sal...  train
997       0  generally , i love sonic . it is by far my fav...  train
998       0  how does this location stay open ? lines are n...  train
999       0  i am not one to visit chain restaurants , but ...  train

[1000 rows x 3 columns]

In [24]:
"""
data shape
review
"sentence"
# split and rating are separated by file name
"""
f1_s = "/home/bwlee/work/codes/controllable/data/amazon/sentiment.train.0"
f2_s = "/home/bwlee/work/codes/controllable/data/amazon/sentiment.train.1"
df1 = pd.read_csv(f1_s, sep='\n', header=None, names=['review'])
df1['rating'] = 0
df1['split'] = 'train'

In [25]:
df1

                                                   review  rating  split
0       especially on moderate where the attacks are c...       0  train
1       i put this on my hair and flat ironed it and m...       0  train
2       since their price is three times that they are...       0  train
3               just had to give it the personal touch .        0  train
4          i cannot find patterns to solve the problem .        0  train
...                                                   ...     ...    ...
277764  i have a full sized houge grip on my glock num...       0  train
277765  there is nothing about this product which warr...       0  train
277766  the only thing it controlled was my hot flashe...       0  train
277767  there s so much personal taste involved when a...       0  train
277768        i think this is one product you can skip .        0  train

[277769 rows x 3 columns]